# Generated by Django 4.1.1 on 2022-12-27 18:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElementPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255, null=True, verbose_name='Поле для ввода')),
                ('html_field', tinymce.models.HTMLField(null=True, verbose_name='HTML поле для ввода')),
            ],
            options={
                'verbose_name': 'Элемент страницы',
                'verbose_name_plural': 'Элементы страницы',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=255, verbose_name='Заголовок h1')),
                ('content', tinymce.models.HTMLField(null=True, verbose_name='Контент')),
                ('seo_title', models.CharField(max_length=255, null=True, verbose_name='Сео заголовок')),
                ('seo_description', models.CharField(max_length=255, null=True, verbose_name='Сео описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('elements', models.ManyToManyField(blank=True, to='page.elementpage', verbose_name='Элементы страницы')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
    ]
