# Generated by Django 4.1.1 on 2022-12-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='Код страницы'),
        ),
    ]
