# Generated by Django 4.1.1 on 2023-01-10 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0004_fileorimage'),
        ('events', '0032_delete_eventcheckin_delete_eventcheckinstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.IntegerField(default=1, verbose_name='Позиция')),
                ('is_banner', models.BooleanField(default=False, verbose_name='Баннер')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('date', models.DateField(verbose_name='Дата')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('position', models.IntegerField(default=1, verbose_name='Позиция')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('events', models.ManyToManyField(blank=True, default=None, to='events.events', verbose_name='Мероприятия')),
                ('genres', models.ManyToManyField(blank=True, default=None, to='events.eventgenre', verbose_name='Жанры')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
    ]
