# Generated by Django 4.1.1 on 2023-01-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_fileorimage'),
        ('design', '0002_alter_rubric_image_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.image', verbose_name='Изображение'),
        ),
    ]
