# Generated by Django 4.1.1 on 2022-09-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('images', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Телефон')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_legal', models.BooleanField(default=False)),
                ('is_email_validated', models.BooleanField(default=False)),
                ('activation_key', models.CharField(blank=True, max_length=40, null=True)),
                ('key_expires', models.DateTimeField(blank=True, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации')),
                ('legal_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес')),
                ('ogrn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=255, null=True, verbose_name='КПП')),
                ('nds', models.BooleanField(default=True, verbose_name='Включать в стоимость билетов НДС')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('bik', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True, verbose_name='Расчетный счет')),
                ('kor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Корр. счет')),
                ('legal_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия подписывающего лица')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя подписывающего лица')),
                ('legal_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество подписывающего лица')),
                ('legal_role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('legal_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Действующий на основании')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.country', verbose_name='Страна')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='Фото')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
