# Generated by Django 4.1.1 on 2022-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abilet',
            field=models.BooleanField(default=True),
        ),
    ]
