# Generated by Django 4.1.1 on 2023-01-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userchecker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tax',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Комиссионный сбор'),
        ),
    ]
