# Generated by Django 4.1.1 on 2023-02-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCheckers',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='users.userchecker', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Токен проверяющего',
                'verbose_name_plural': 'Токены проверяющего',
            },
        ),
    ]
