# Generated by Django 4.1.1 on 2023-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tokencheckers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unisender',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='Действующий на основании'),
        ),
    ]
