# Generated by Django 4.1.1 on 2023-03-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_unisender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key_expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unisender',
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
