# Generated by Django 4.1.1 on 2023-03-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_key_expires_remove_user_unisender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='smscode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
