# Generated by Django 4.1.1 on 2022-12-14 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0004_fileorimage'),
        ('events', '0026_eventareaschems_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None, verbose_name='Дата создания')),
                ('type', models.CharField(choices=[('sms', 'СМС'), ('email', 'Почта')], max_length=255, verbose_name='Тип рассылки')),
                ('toeveryone', models.BooleanField(default=False, verbose_name='Разослать всем пользователям')),
                ('text', models.TextField(blank=True, default=None, null=True, verbose_name='Текст сообщения')),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.events', verbose_name='Пользователь')),
                ('files', models.ManyToManyField(blank=True, default=None, to='images.fileorimage')),
                ('users', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
