# Generated by Django 4.1.1 on 2022-12-15 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventareaschems_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='users',
        ),
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='user_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='event',
        ),
        migrations.AddField(
            model_name='mailing',
            name='event',
            field=models.ManyToManyField(blank=True, default=None, to='events.events', verbose_name='Пользователь'),
        ),
    ]
