# Generated by Django 4.1.1 on 2023-04-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(default=None, verbose_name='Дата запуска'),
        ),
    ]
