# Generated by Django 4.1.1 on 2022-09-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('images', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код жанра мероприятия')),
                ('name', models.CharField(max_length=255, verbose_name='Название жанра мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('raising', models.IntegerField(blank=True, null=True, verbose_name='Повысить после n продаж')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='По дате')),
            ],
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код статуса мероприятия')),
                ('name', models.CharField(max_length=255, verbose_name='Название статуса мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tax', models.IntegerField(default=0, verbose_name='Сервисный сбор')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Дата проведения')),
                ('finish_date', models.DateField(auto_now=True, verbose_name='Дата закрытия продаж')),
                ('is_showcase', models.BooleanField(default=False, verbose_name='Рекламма на витрине сайта')),
                ('afisha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afisha', to='images.image', verbose_name='Афиша')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.city', verbose_name='Города')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventgenre', verbose_name='Жанр')),
                ('payment', models.ManyToManyField(to='payment.payment', verbose_name='Способ оплаты')),
                ('preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='images.image', verbose_name='Анонс')),
                ('price', models.ManyToManyField(to='events.eventprice', verbose_name='Цена')),
                ('stage_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_image', to='images.image', verbose_name='Вид зала')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventstatus', verbose_name='Статус')),
            ],
        ),
    ]
