# Generated by Django 4.1.1 on 2022-10-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgenre',
            options={'verbose_name': 'Жанр мероприятия', 'verbose_name_plural': 'Жанры мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventprice',
            options={'verbose_name': 'Цена мероприятия', 'verbose_name_plural': 'Цены мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventstatus',
            options={'verbose_name': 'Статус мероприятия', 'verbose_name_plural': 'Статусы мероприятия'},
        ),
    ]
