# Generated by Django 4.1.1 on 2022-10-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventgenre_options_alter_eventprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Ограничение возраста мероприятия')),
                ('name', models.CharField(max_length=255, verbose_name='Ограничение возраста мероприятия')),
            ],
            options={
                'verbose_name': 'Ограничение возраста мероприятия',
                'verbose_name_plural': 'Ограничения возраста мероприятия',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='age',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='age', to='events.eventage', verbose_name='Ограничение возраста'),
        ),
    ]
