# Generated by Django 4.1.1 on 2022-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventage_events_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventage',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Код ограничение возраста мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Количество ограничение возраста мероприятия'),
        ),
    ]
