# Generated by Django 4.1.1 on 2022-10-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventprice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_main_slider',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Выводить в слайдере на главной'),
        ),
    ]
