# Generated by Django 4.1.1 on 2022-10-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_events_is_main_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='is_main_slider',
            field=models.BooleanField(default=False, verbose_name='Выводить в слайдере на главной'),
        ),
    ]
