# Generated by Django 4.1.1 on 2022-10-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_events_is_main_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код типа мероприятия')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа мероприятия')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Тип мероприятия',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='is_expected',
            field=models.BooleanField(default=False, verbose_name='Ожидаемый'),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventtype', verbose_name='Тип'),
        ),
    ]
