# Generated by Django 4.1.1 on 2022-10-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_events_for_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='finish_date',
            field=models.DateField(verbose_name='Дата закрытия продаж'),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
    ]
