# Generated by Django 4.1.1 on 2022-10-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_city_options_alter_country_options_and_more'),
        ('events', '0013_alter_eventarea_options_alter_events_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventarea',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Адрес площадки'),
        ),
        migrations.AddField(
            model_name='eventarea',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.city', verbose_name='Город'),
        ),
    ]
