# Generated by Django 4.1.1 on 2022-10-22 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
        ('events', '0014_eventarea_address_eventarea_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventarea',
            name='gallery',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='eventarea',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, null=True, srid=4326),
        ),
    ]
