# Generated by Django 4.1.1 on 2022-10-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
        ('events', '0015_eventarea_gallery_eventarea_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventarea',
            name='gallery',
        ),
        migrations.AddField(
            model_name='eventarea',
            name='gallery',
            field=models.ManyToManyField(default=None, null=True, to='images.image', verbose_name='Галерея'),
        ),
    ]
