# Generated by Django 4.1.1 on 2022-10-22 14:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
        ('events', '0016_remove_eventarea_gallery_eventarea_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventarea',
            name='gallery',
            field=models.ManyToManyField(default=None, to='images.image', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='eventarea',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, geography=True, null=True, srid=4326),
        ),
    ]
