# Generated by Django 4.1.1 on 2022-10-25 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0018_eventfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAreaPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Место')),
                ('row', models.CharField(max_length=255, null=True, verbose_name='Ряд')),
            ],
            options={
                'verbose_name': 'Стандартное место схемы',
                'verbose_name_plural': 'Стандартные места схем',
            },
        ),
        migrations.AlterField(
            model_name='eventarea',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Количество площадки мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventprice',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='EventAreaSchems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scheme', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название схемы площадки')),
                ('schem', models.TextField(verbose_name='Схема сцены')),
                ('places', models.ManyToManyField(default=None, null=True, to='events.eventareaplaces', verbose_name='Места')),
            ],
            options={
                'verbose_name': 'Cхема зала',
                'verbose_name_plural': 'Схемы зала',
            },
        ),
        migrations.CreateModel(
            name='EventAreaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('count', models.IntegerField(default=None, max_length=255, null=True, verbose_name='Количество билетов')),
                ('scheme', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventareaschems', verbose_name='Схема')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Площадка мероприятия',
                'verbose_name_plural': 'Площадки мероприятия',
            },
        ),
        migrations.AddField(
            model_name='eventarea',
            name='schems',
            field=models.ManyToManyField(default=None, to='events.eventareaschems', verbose_name='Схемы зала'),
        ),
        migrations.AddField(
            model_name='eventprice',
            name='place',
            field=models.ManyToManyField(default=None, null=True, to='events.eventareaplaces', verbose_name='Место'),
        ),
    ]
