# Generated by Django 4.1.1 on 2022-10-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventareaplaces_alter_eventarea_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventareacategory',
            options={'verbose_name': 'Категория цен', 'verbose_name_plural': 'Категории цен'},
        ),
        migrations.RemoveField(
            model_name='events',
            name='price',
        ),
        migrations.AlterField(
            model_name='eventarea',
            name='schems',
            field=models.ManyToManyField(to='events.eventareaschems', verbose_name='Схемы зала'),
        ),
        migrations.AlterField(
            model_name='eventareacategory',
            name='count',
            field=models.IntegerField(default=None, null=True, verbose_name='Количество билетов'),
        ),
        migrations.AlterField(
            model_name='eventareaschems',
            name='places',
            field=models.ManyToManyField(to='events.eventareaplaces', verbose_name='Места'),
        ),
        migrations.AlterField(
            model_name='eventareaschems',
            name='schem',
            field=models.TextField(blank=True, null=True, verbose_name='Схема сцены'),
        ),
        migrations.AlterField(
            model_name='eventprice',
            name='place',
            field=models.ManyToManyField(to='events.eventareaplaces', verbose_name='Место'),
        ),
    ]
