# Generated by Django 4.1.1 on 2022-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_eventareacategory_options_remove_events_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventareaschems',
            name='is_scheme',
        ),
        migrations.AddField(
            model_name='eventarea',
            name='is_scheme',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventareacategory',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
