# Generated by Django 4.1.1 on 2022-11-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_eventareaschems_is_scheme_eventarea_is_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprice',
            name='up_price',
            field=models.BooleanField(default=False, verbose_name='Повысить цену после'),
        ),
    ]
