# Generated by Django 4.1.1 on 2022-12-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_eventprice_up_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprice',
            name='place',
            field=models.ManyToManyField(default=None, to='events.eventareaplaces', verbose_name='Место'),
        ),
    ]
