# Generated by Django 4.1.1 on 2022-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_eventprice_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprice',
            name='place',
            field=models.ManyToManyField(blank=True, default=None, to='events.eventareaplaces', verbose_name='Место'),
        ),
    ]
