# Generated by Django 4.1.1 on 2022-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
        ('events', '0025_eventareacategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventareaschems',
            name='preview',
            field=models.ManyToManyField(default=None, to='images.image', verbose_name='Превью схемы'),
        ),
    ]
