# Generated by Django 4.1.1 on 2023-01-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventareaschems_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventareacategory',
            name='evented',
            field=models.BooleanField(default=False, verbose_name='Принадлежит к мероприятию'),
        ),
        migrations.AddField(
            model_name='eventprice',
            name='evented',
            field=models.BooleanField(default=False, verbose_name='Принадлежит к мероприятию'),
        ),
        migrations.AddField(
            model_name='events',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, to='events.eventareacategory', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='events',
            name='prices',
            field=models.ManyToManyField(blank=True, default=None, to='events.eventprice', verbose_name='Цены'),
        ),
    ]
