# Generated by Django 4.1.1 on 2023-01-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userchecker'),
        ('events', '0027_eventareacategory_evented_eventprice_evented_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCheckinStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=255, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус чекина',
                'verbose_name_plural': 'Статусы чекина',
            },
        ),
        migrations.CreateModel(
            name='EventCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='events.eventareacategory', verbose_name='Категория мероприятия')),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userchecker', verbose_name='Проверяющий')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events', verbose_name='Мероприятие')),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='events.eventareaplaces', verbose_name='Место мероприятия')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventcheckinstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Чекин',
                'verbose_name_plural': 'Чекины',
            },
        ),
    ]
