# Generated by Django 4.1.1 on 2023-01-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_eventcheckinstatus_eventcheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcheckin',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='events.eventareacategory', verbose_name='Категория мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventcheckin',
            name='place',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='events.eventareaplaces', verbose_name='Место мероприятия'),
        ),
    ]
