# Generated by Django 4.1.1 on 2023-01-02 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_eventcheckin_category_alter_eventcheckin_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcheckin',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
