# Generated by Django 4.1.1 on 2023-01-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_eventcheckin_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventCheckin',
        ),
        migrations.DeleteModel(
            name='EventCheckinStatus',
        ),
    ]
