# Generated by Django 4.1.1 on 2023-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_delete_eventcheckin_delete_eventcheckinstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgenre',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Код жанра мероприятия'),
        ),
    ]
