# Generated by Django 4.1.1 on 2023-01-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_remove_eventarea_is_scheme_remove_events_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventarea',
            name='is_scheme',
            field=models.BooleanField(default=True, verbose_name='Схема'),
        ),
    ]
