# Generated by Django 4.1.1 on 2023-01-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0035_eventarea_is_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventareacategory',
            name='event',
            field=models.ManyToManyField(blank=True, to='events.events', verbose_name='Мероприятия'),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='schemes',
            field=models.ManyToManyField(blank=True, to='events.eventareaschems', verbose_name='Схемы'),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='eventprice',
            name='event',
            field=models.ManyToManyField(blank=True, to='events.events', verbose_name='Мероприятия'),
        ),
        migrations.RemoveField(
            model_name='eventareacategory',
            name='scheme',
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='event',
            field=models.ManyToManyField(blank=True, to='events.events', verbose_name='Мероприятия'),
        ),
        migrations.AddField(
            model_name='eventareacategory',
            name='scheme',
            field=models.ManyToManyField(blank=True, default=None, to='events.eventareaschems', verbose_name='Схема'),
        ),
    ]
