# Generated by Django 4.1.1 on 2023-01-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_eventareacategory_event_eventdate_schemes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventprice',
            name='evented',
        ),
    ]
