# Generated by Django 4.1.1 on 2023-01-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_remove_eventprice_evented'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventareaschems',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, to='events.eventareacategory', verbose_name='Категории цен'),
        ),
        migrations.AddField(
            model_name='eventareaschems',
            name='dates',
            field=models.ManyToManyField(blank=True, default=None, to='events.eventdate', verbose_name='Даты схемы'),
        ),
    ]
