# Generated by Django 4.1.1 on 2023-01-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_eventareaplaces_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventareaschems',
            name='prices',
            field=models.ManyToManyField(blank=True, default=None, to='events.eventprice', verbose_name='Цены'),
        ),
        migrations.AddField(
            model_name='eventprice',
            name='schemes',
            field=models.ManyToManyField(blank=True, default=None, to='events.eventareaschems', verbose_name='Схемы'),
        ),
    ]
