# Generated by Django 4.1.1 on 2023-01-20 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_fileorimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0040_eventareaschems_prices_eventprice_schemes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention', models.TextField(blank=True, default=None, null=True, verbose_name='Блок внимание')),
                ('is_attention', models.BooleanField(default=False, verbose_name='Блок внимание по стандарту')),
                ('returning', models.TextField(blank=True, default=None, null=True, verbose_name='Блок правила возврата')),
                ('is_returning', models.BooleanField(default=False, verbose_name='Блок правила возврата по стандарту')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Блок о событии')),
                ('is_description', models.BooleanField(default=False, verbose_name='Блок о событии по стандарту')),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.image', verbose_name='Картинка шаблона')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Шаблоны для печати',
                'verbose_name_plural': 'Шаблон для печати',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='mail_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventmailtemplate', verbose_name='Шаблон для печати'),
        ),
    ]
