# Generated by Django 4.1.1 on 2023-01-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_eventmailtemplate_events_mail_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='mail_template',
        ),
        migrations.AddField(
            model_name='eventmailtemplate',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Мероприятие'),
        ),
    ]
