# Generated by Django 4.1.1 on 2023-01-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_logo'),
        ('images', '0004_fileorimage'),
        ('events', '0042_remove_events_mail_template_eventmailtemplate_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='payment',
            field=models.ManyToManyField(blank=True, default=None, to='payment.payment', verbose_name='Способ оплаты'),
        ),
        migrations.RemoveField(
            model_name='events',
            name='stage_image',
        ),
        migrations.AddField(
            model_name='events',
            name='stage_image',
            field=models.ManyToManyField(blank=True, default=None, to='images.image', verbose_name='Вид зала'),
        ),
    ]
