# Generated by Django 4.1.1 on 2023-01-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_alter_events_payment_remove_events_stage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
