# Generated by Django 4.1.1 on 2023-01-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_fileorimage'),
        ('events', '0044_alter_events_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='afisha',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afisha', to='images.image', verbose_name='Афиша'),
        ),
        migrations.AlterField(
            model_name='events',
            name='preview',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='images.image', verbose_name='Анонс'),
        ),
    ]
