# Generated by Django 4.1.1 on 2023-01-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_alter_events_afisha_alter_events_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventareacategory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален пользователем'),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален пользователем'),
        ),
        migrations.AddField(
            model_name='eventprice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален пользователем'),
        ),
    ]
