# Generated by Django 4.1.1 on 2023-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_alter_eventarea_schems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ManyToManyField(default=None, to='events.eventtype', verbose_name='Тип'),
        ),
    ]
