# Generated by Django 4.1.1 on 2023-03-03 18:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_alter_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventarea',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, geography=True, null=True, srid=4326),
        ),
    ]
