# Generated by Django 4.1.1 on 2023-03-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_alter_eventarea_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='genre',
        ),
        migrations.AddField(
            model_name='events',
            name='genre',
            field=models.ManyToManyField(to='events.eventgenre', verbose_name='Жанр'),
        ),
    ]
