# Generated by Django 4.1.1 on 2023-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_remove_events_genre_events_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='genre',
            field=models.ManyToManyField(blank=True, default=None, to='events.eventgenre', verbose_name='Жанр'),
        ),
    ]
