# Generated by Django 4.1.1 on 2023-03-16 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0052_alter_events_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название промоакции')),
                ('start_date', models.DateField(verbose_name='Начало действия')),
                ('finish_date', models.DateField(verbose_name='Окончание действия')),
                ('template', models.CharField(blank=True, choices=[('TWONE', '2+1'), ('THREEONE', '3+1')], max_length=255, null=True, verbose_name='Шаблон')),
                ('template_descr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('fix_sum', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер скидки')),
                ('fix_count', models.IntegerField(blank=True, null=True, verbose_name='Количество билетов')),
                ('dynamic_sum', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма заказа от')),
                ('dynamic_count', models.IntegerField(blank=True, null=True, verbose_name='Количество билетов')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.events', verbose_name='Мероприятия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Промоакции',
                'verbose_name_plural': 'Промоакция',
            },
        ),
    ]
