# Generated by Django 4.1.1 on 2023-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_eventpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpromotion',
            name='type',
            field=models.CharField(choices=[('TEMPLATE', 'Шаблонная'), ('FIX', 'Фиксированная'), ('DYNAMIC', 'Динамическая')], default='TEMPLATE', max_length=255, verbose_name='Тип промоакций'),
        ),
        migrations.AlterField(
            model_name='eventpromotion',
            name='dynamic_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество динамическое'),
        ),
        migrations.AlterField(
            model_name='eventpromotion',
            name='dynamic_sum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Процент или сумма'),
        ),
        migrations.AlterField(
            model_name='eventpromotion',
            name='fix_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество фиксированное'),
        ),
        migrations.AlterField(
            model_name='eventpromotion',
            name='fix_sum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Процент или сумма'),
        ),
        migrations.AlterField(
            model_name='eventpromotion',
            name='template',
            field=models.CharField(blank=True, choices=[('TWONE', '2+1'), ('THREEONE', '3+1')], max_length=255, null=True, verbose_name='Тип шаблона'),
        ),
        migrations.AlterField(
            model_name='eventpromotion',
            name='template_descr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип шаблона'),
        ),
    ]
