# Generated by Django 4.1.1 on 2023-04-13 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_events_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
