# Generated by Django 4.1.1 on 2023-04-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_events_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='update_at',
        ),
    ]
