# Generated by Django 4.1.1 on 2023-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_remove_events_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprice',
            name='raising',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Повысить после n продаж'),
        ),
    ]
