# Generated by Django 4.1.1 on 2022-11-03 19:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0021_remove_eventareaschems_is_scheme_eventarea_is_scheme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_payment_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='Товар принадлежит к заказу')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('f_user', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Идентификатор для незарегистрированных пользователей')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('price', models.IntegerField(default=0, verbose_name='Цена продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CheckoutStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, verbose_name='Код')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус оплаты',
                'verbose_name_plural': 'Статусы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(max_length=255, verbose_name='Название скидки')),
                ('start_date', models.DateField(verbose_name='Начало действия')),
                ('finish_date', models.DateField(verbose_name='Окончание действия')),
                ('count', models.IntegerField(null=True, verbose_name='Количество использований')),
                ('value', models.IntegerField(verbose_name='Размер скидки')),
                ('point', models.CharField(choices=[('percent', 'Процент'), ('cash', 'Точная сумма')], max_length=255, verbose_name='Название скидки')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('price', models.IntegerField(default=0, verbose_name='Цена продукта')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.payment', verbose_name='Способ оплаты')),
                ('products', models.ManyToManyField(to='bao.basket')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bao.checkoutstatus', verbose_name='Способ оплаты')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
