# Generated by Django 4.1.1 on 2022-12-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventareaschems_preview'),
        ('bao', '0004_alter_discount_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.events', verbose_name='Пользователь'),
        ),
    ]
