# Generated by Django 4.1.1 on 2022-12-18 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0007_rename_checkoureturn_checkoutreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutreturn',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bao.checkoutstatus', verbose_name='Статус оплаты'),
        ),
    ]
