# Generated by Django 4.1.1 on 2023-01-02 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userchecker'),
        ('bao', '0009_alter_checkoutreturn_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCheckinStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=255, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус чекина',
                'verbose_name_plural': 'Статусы чекина',
            },
        ),
        migrations.CreateModel(
            name='EventCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userchecker', verbose_name='Проверяющий')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bao.checkout', verbose_name='Заказ')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bao.eventcheckinstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Чекин',
                'verbose_name_plural': 'Чекины',
            },
        ),
    ]
