# Generated by Django 4.1.1 on 2023-01-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_delete_eventcheckin_delete_eventcheckinstatus'),
        ('bao', '0010_eventcheckinstatus_eventcheckin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.events', verbose_name='Мероприятия'),
        ),
    ]
