# Generated by Django 4.1.1 on 2023-01-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_remove_eventarea_is_scheme_remove_events_finish_date_and_more'),
        ('bao', '0011_alter_discount_options_alter_discount_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='date',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventdate', verbose_name='Дата'),
        ),
    ]
