# Generated by Django 4.1.1 on 2023-01-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_alter_events_afisha_alter_events_preview'),
        ('bao', '0012_basket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.events', verbose_name='Мероприятия'),
        ),
    ]
