# Generated by Django 4.1.1 on 2023-01-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_alter_events_afisha_alter_events_preview'),
        ('bao', '0013_alter_discount_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventprice', verbose_name='Цена'),
        ),
    ]
