# Generated by Django 4.1.1 on 2023-01-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_alter_events_afisha_alter_events_preview'),
        ('bao', '0014_alter_basket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='price',
        ),
        migrations.AddField(
            model_name='basket',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventareacategory', verbose_name='Категория цен'),
        ),
    ]
