# Generated by Django 4.1.1 on 2023-01-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0015_remove_checkout_price_basket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='pricing',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
