# Generated by Django 4.1.1 on 2023-01-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0016_basket_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален пользователем'),
        ),
    ]
