# Generated by Django 4.1.1 on 2023-01-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_eventareacategory_is_deleted_eventdate_is_deleted_and_more'),
        ('bao', '0017_discount_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.eventareaplaces', verbose_name='Место в зале'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='discount_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Тип скидки'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='discount_value',
            field=models.IntegerField(default=0, verbose_name='Количество скидки'),
        ),
    ]
