# Generated by Django 4.1.1 on 2023-01-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0018_basket_place_checkout_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='Размер скидки'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость заказа без скидки'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='discount_value',
            field=models.IntegerField(default=0, verbose_name='Стоимость заказа со скидкой'),
        ),
    ]
