# Generated by Django 4.1.1 on 2023-01-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0020_alter_checkout_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='discount_value',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
    ]
