# Generated by Django 4.1.1 on 2023-01-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0021_alter_checkout_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость заказа со скидкой'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='tax',
            field=models.IntegerField(default=0, verbose_name='Налог пользователя'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='discount_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Тип скидки указанный пользователя'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='discount_value',
            field=models.IntegerField(default=0, verbose_name='Скидка указанная пользователем'),
        ),
    ]
