# Generated by Django 4.1.1 on 2023-01-29 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0022_checkout_discount_price_checkout_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
