# Generated by Django 4.1.1 on 2023-02-01 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0023_alter_checkout_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
