# Generated by Django 4.1.1 on 2023-02-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0024_alter_basket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='qr_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Код qr'),
        ),
    ]
