# Generated by Django 4.1.1 on 2023-02-07 23:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0025_basket_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcheckin',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bao.basket', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
    ]
