# Generated by Django 4.1.1 on 2023-02-07 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bao', '0026_eventcheckin_product_alter_basket_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcheckin',
            name='checkout',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bao.checkout', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='eventcheckin',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='bao.basket', verbose_name='Товар'),
        ),
    ]
