# Generated by Django 4.1.1 on 2022-12-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код вопроса')),
                ('name', models.CharField(max_length=255, verbose_name='Название вопроса')),
            ],
            options={
                'verbose_name': 'Категория вопросов',
                'verbose_name_plural': 'Категории вопросов',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, verbose_name='Тема вопроса')),
                ('text', models.TextField(verbose_name='Описание')),
                ('order', models.CharField(max_length=255, verbose_name='Номер заказа')),
                ('event_name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('elements', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.questions', verbose_name='Категория вопросов')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
    ]
