# Generated by Django 4.1.1 on 2023-01-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0032_delete_eventcheckin_delete_eventcheckinstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('events', models.ManyToManyField(blank=True, default=None, to='events.events', verbose_name='Мероприятия')),
                ('genres', models.ManyToManyField(blank=True, default=None, to='events.eventgenre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Спецпредложение',
                'verbose_name_plural': 'Спецпредложения',
            },
        ),
    ]
