# Generated by Django 4.1.1 on 2022-11-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
        ('payment', '0002_alter_payment_options_payment_code_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='logo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='Логотип'),
        ),
    ]
