# Generated by Django 4.1.1 on 2022-12-24 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код периода отчета')),
                ('name', models.CharField(max_length=255, verbose_name='Название периода отчета')),
                ('period', models.IntegerField(default=1, verbose_name='Период времени в минутах')),
            ],
            options={
                'verbose_name': 'Период отчета',
                'verbose_name_plural': 'Периоды отчета',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код вида отчета')),
                ('name', models.CharField(max_length=255, verbose_name='Название вида отчета')),
            ],
            options={
                'verbose_name': 'Вид отчета',
                'verbose_name_plural': 'Виды отчета',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('period', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.reportperiod', verbose_name='Периоды отчета')),
                ('type', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.reporttype', verbose_name='Вид отчета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус мероприятия',
                'verbose_name_plural': 'Статусы мероприятия',
            },
        ),
    ]
