# Generated by Django 4.1.1 on 2022-12-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
