# Generated by Django 4.1.1 on 2023-03-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reports_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
    ]
