# Generated by Django 4.1.1 on 2022-10-12 13:59

import app.images.models
from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=thumbnails.fields.ImageField(height_field='height', max_length=255, upload_to=app.images.models.get_realestate_photo_filename, width_field='width'),
        ),
    ]
