# Generated by Django 4.1.1 on 2022-12-14 20:12

import app.images.models
from django.db import migrations, models
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileOrImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', thumbnails.fields.ImageField(height_field='height', max_length=255, upload_to=app.images.models.get_realestate_photo_filename, width_field='width')),
                ('width', models.IntegerField(default=0, editable=False)),
                ('height', models.IntegerField(default=0, editable=False)),
                ('is_main', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Внешняя ссылка')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
